#!/usr/bin/env bash
# scripts/build-release.sh
#
# Build a signed release APK for Whispera4Android.
#
# Requires that keystore.properties exists at the repo root (generated by
# ./scripts/gen-keystore.sh). Gradle picks up that file automatically.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"

# Check that the sherpa-onnx AAR has been downloaded by setup_models.sh.
AAR="app/libs/sherpa-onnx-1.13.4.aar"
if [[ ! -f "$AAR" ]]; then
  echo "✗ $AAR not found. Run ./scripts/setup_models.sh first."
  exit 1
fi

PROPS="keystore.properties"
if [[ ! -f "$PROPS" ]]; then
  echo "✗ keystore.properties not found at repo root."
  echo "  Run ./scripts/gen-keystore.sh once to generate a release keystore."
  echo "  (see scripts/gen-keystore.sh for details; the output is gitignored by .gitignore)."
  exit 1
fi

flavor="${1:-offlineFull}"
echo "Assembling $flavor / release (signed) …"
./gradlew "assemble${flavor^}Release" --console=plain --info
APK="${REPO_ROOT}/app/build/outputs/apk/${flavor}/release/app-${flavor}-release-unsigned.apk"
# If signing wired up, the filename does NOT include the -unsigned suffix.
SIGNED="${REPO_ROOT}/app/build/outputs/apk/${flavor}/release/app-${flavor}-release.apk"
if [[ -f "$SIGNED" ]]; then APK="$SIGNED"; fi

echo
echo "✓ Built release APK: $APK"
ls -lh "$APK"
echo
echo "Install on a connected device:"
echo "  ./scripts/install.sh $APK"
