#!/usr/bin/env bash
# scripts/gen-keystore.sh
#
# Generates a release keystore for signing Whispera4Android APKs.
#
# Usage:
#   ./scripts/gen-keystore.sh                          # interactive: prompts for passwords
#   ./scripts/gen-keystore.sh --auto                   # default demo password "whispera" (⚠ self-test only)
#
# After this script runs you fill in keystore.properties (a template) once and
# `./scripts/build-release.sh` will sign the release APK automatically.
#
# SECURITY: the generated keystore (release-key.jks) and keystore.properties MUST
# stay local — they are listed in .gitignore. NEVER commit them to the repository.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

KS="$REPO_ROOT/release-key.jks"
PROPS="$REPO_ROOT/keystore.properties"

auto=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --auto) auto=1; shift ;;
    *) echo "Unknown flag: $1"; exit 2 ;;
  esac
done

if ! command -v keytool >/dev/null; then
  echo "✗ 'keytool' not found. Install a JDK or Android Studio first (JDK 17+ recommended)."
  exit 1
fi

if [[ -f "$KS" ]]; then
  echo "Existing keystore at $KS — refusing to overwrite. Delete or rename it first."
  exit 1
fi

if [[ $auto -eq 1 ]]; then
  storepass="whispera"
  keypass="whispera"
  alias="whispera-release"
  cn="Whispera4Android"
  echo "⚠ --auto mode: using demo password '$storepass'. Use ONLY for self-signed testing."
else
  read -s -p "Keystore password: " storepass; echo
  read -s -p "Key password (blank = same as keystore): " keypass; echo
  [[ -z "$keypass" ]] && keypass="$storepass"
  read -p "Key alias [whispera-release]: " alias
  [[ -z "$alias" ]] && alias="whispera-release"
  read -p "CN (Your name) [Whispera4Android]: " cn
  [[ -z "$cn" ]] && cn="Whispera4Android"
fi

echo "Generating keystore at $KS"
keytool -genkeypair -v \
  -keystore "$KS" \
  -storetype JKS \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -alias "$alias" \
  -storepass "$storepass" \
  -keypass "$keypass" \
  -dname "CN=$cn, O=Whispera4Android, C=Unknown" \
  -ext "BasicConstraints=CA:FALSE" -ext "KeyUsage=digitalSignature,keyEncipherment" \
  -ext "ExtendedKeyUsage=codeSigning"

# Write keystore.properties so the gradle build picks it up automatically.
write_props() {
cat > "$PROPS" <<EOF
# Generated by scripts/gen-keystore.sh — DO NOT COMMIT THIS FILE.
# The pointers below tell Gradle which keystore + password to use when signing
# release APKs. See app/build.gradle.kts (signingConfigs block).
storeFile=$KS
storePassword=$storepass
keyAlias=$alias
keyPassword=$keypass
EOF
}
write_props
chmod 600 "$PROPS" "$KS"

echo
echo "✓ Keystore:    $KS"
echo "✓ Properties:  $PROPS"
echo
echo "Now run: ./scripts/build-release.sh"
echo
echo "⚠ $PROPS and $KS are excluded by .gitignore — verify they're ignored before committing."
